"""empty message

Revision ID: 411a7218824e
Revises: c7b0421d0527
Create Date: 2018-07-27 14:54:04.896904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411a7218824e'
down_revision = 'c7b0421d0527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'author_id')
    # ### end Alembic commands ###
