"""empty message

Revision ID: 899f0f520bd1
Revises:
Create Date: 2018-07-14 23:27:11.140683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899f0f520bd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('status', sa.SmallInteger(), server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'status')
    # ### end Alembic commands ###
